<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Titan BOS — Zero BS.</title>
    <meta name="description" content="The AI operating system built for cleaning businesses. Titan runs the business. Zero removes the friction.">
    <script src="https://cdn.tailwindcss.com"></script>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <style>
        [x-cloak]{display:none!important}
        .grid-bg{background-image:linear-gradient(rgba(255,255,255,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.06) 1px,transparent 1px);background-size:42px 42px;}
    </style>
</head>
<body class="bg-black text-white antialiased">
@php
    $apps = [
        ['tier'=>'FIELD EXECUTION','name'=>'Titan Go','icon'=>'📱','category'=>'Guided Work Engine','owns'=>'work correctness','tagline'=>'Field Execution Operating System','impact'=>'2–3 more hours cleaning. Zero dispute callbacks.','features'=>['Context-aware checklist mutation (adapts to site, weather, risk)','Evidence confidence engine (requests retakes automatically)','Technician skill matching (hides unauthorized tasks)','Offline-first evidence chain (legal-grade documentation)','Completion confidence score (predicts inspection pass)']],
        ['tier'=>'OPERATIONS','name'=>'Ground Zero','icon'=>'🎯','category'=>'Stage-Aware Dispatch System','owns'=>'execution timing','tagline'=>'Lifecycle Orchestration Engine','impact'=>'More jobs per tech. Fewer domino failures. Higher SLA compliance.','features'=>['Lifecycle graph scheduling (schedules states, not slots)','Constraint-aware dispatch AI (multi-variable optimization)','Zone-based work mapping (spatial dispatch for construction)','Delay cascade simulation (predicts downstream impacts)','Dispatch risk meter (warns of failures before they occur)']],
        ['tier'=>'CONTRACT','name'=>'Titan Pro','icon'=>'📊','category'=>'Service Performance Command System','owns'=>'decision visibility','tagline'=>'Operational Intelligence Layer','impact'=>'Spot problem sites early. Prevent revenue leakage. Drive strategy.','features'=>['Intervention radar (alerts on failures before they occur)','Margin heatmap by service type (immediate profitability insight)','Compliance exposure index (certification gaps, audit risk)','Client risk forecasting (churn, complaints, late payments)','Workforce load stability score (burnout pattern detection)']],
        ['tier'=>'SOLO','name'=>'Titan Solo','icon'=>'👤','category'=>'Operator Autopilot System','owns'=>'operator stability','tagline'=>'Independent Operator OS','impact'=>'Less admin burden. Predictable recurring revenue. Clear growth path.','features'=>['Daily route optimizer (travel, job order, breaks, supplies)','Income stability predictor (forecasts revenue variance)','Smart repeat booking engine (auto-detects renewal opportunities)','One-tap completion accounting (invoice+payment+follow-up)','Capacity expansion advisor (tells when to hire first staff)']],
        ['tier'=>'COMMS','name'=>'Titan Hello','icon'=>'💬','category'=>'Conversational Operations Gateway','owns'=>'service entry','tagline'=>'Autonomous Service Front Door','impact'=>'15–20% higher rebooking. Fewer field surprises. Better data quality.','features'=>['Intent-to-job engine (detects quote, urgent, inspection, renewal, complaint)','Multi-channel conversation memory (SMS→email→portal→voice continuity)','Smart scope builder (builds property profile before scheduling)','Booking confidence scoring (flags inspection risk, complexity)','Pre-dispatch readiness validation (confirms access before dispatch)']],
        ['tier'=>'AI','name'=>'Titan Zero','icon'=>'🧠','category'=>'Operational Knowledge Infrastructure','owns'=>'institutional intelligence','tagline'=>'Service Mode Intelligence Engine','impact'=>'Faster onboarding. Fewer compliance mistakes. Institutional knowledge stays.','features'=>['Procedural memory layer (remembers how your company works)','Inspection strategy advisor (predicts what inspectors check)','Training gap detector (identifies skill gaps preemptively)','Artefact auto-composer (photos+checklist+notes→bond pack)','Policy translator (standard→executable checklist logic)']],
        ['tier'=>'PAY','name'=>'ZeroPay','icon'=>'💳','category'=>'Payment Operations Layer','owns'=>'revenue completion','tagline'=>'Revenue Completion Engine','impact'=>'Instant on-site collection. Better cash flow. Higher margins.','features'=>['Payment sessions (secure, device-first payable objects)','QR code payments (invoice, deposit, static, dynamic, fallback)','Payment links (email, SMS, portal, printed invoice, mobile)','PayID, bank transfer, and cash-first rails','AI-assisted follow-up and reconciliation queues']],
        ['tier'=>'PROPERTY','name'=>'Zero Fuss','icon'=>'🔑','category'=>'Service Relationship Automation Engine','owns'=>'trust continuity','tagline'=>'Client Experience Layer','impact'=>'More PM referrals. Smoother renewals. Fewer disputes.','features'=>['Expectation alignment engine (confirms arrival, outcome, access)','Readiness confirmation layer (proactive property staging updates)','Evidence delivery streams (live timeline instead of attachments)','Satisfaction prediction engine (detects dissatisfaction early)','Silent approval detection (learns client acceptance patterns)']],
        ['tier'=>'GROWTH','name'=>'Titan Studio','icon'=>'📚','category'=>'Vertical-Aware Demand Generator','owns'=>'demand creation','tagline'=>'Service Growth Engine','impact'=>'Built-in growth engine. Consistent quality. Predictable demand.','features'=>['Service gap detection (identifies undersupplied local Service Modes)','Seasonality opportunity engine (auto-triggers campaign windows)','Reputation flywheel automation (optimal review timing)','Upsell opportunity detection (suggests adjacent services)','Local authority positioning engine (builds inspection-ready brand)']],
    ];
    $modes = [
        'residential'=>['name'=>'Residential Cleaning','workflows'=>['Pre-clean walkthrough','Cleaning execution','Post-clean inspection','Client sign-off'],'compliance'=>['Insurance requirements','Customer complaint handling','Safety protocols'],'artifacts'=>['Handover reports','Before/after galleries','Warranty documentation']],
        'bond'=>['name'=>'Bond Cleaning','workflows'=>['Inventory check','Deep clean phases','Bond schedule inspection','Compliance documentation'],'compliance'=>['Bond schedule adherence','Real estate handoff requirements','Dispute resolution evidence'],'artifacts'=>['Bond packs','Inspection reports','Real estate agent summaries']],
        'pressure'=>['name'=>'Pressure Washing','workflows'=>['Surface assessment','Equipment selection','Pressure application','Before/after proof'],'compliance'=>['Damage risk assessment','Surface-specific protocols','Equipment safety checks'],'artifacts'=>['Damage reports','Surface assessments','Service warranties']],
        'solar'=>['name'=>'Solar Panel Cleaning','workflows'=>['Safety harness verification','Water quality checks','Panel cleaning','Performance verification'],'compliance'=>['Electrical safety','Roof access permits','Warranty protection'],'artifacts'=>['Performance reports','Safety certifications','Maintenance logs']],
    ];
    $zeroPillars = [
        ['icon'=>'💸','title'=>'Zero Hidden Pricing','problem'=>'SaaS tools nickel-and-dime cleaning operators with per-user seats, per-API charges, and surprise overages.','solution'=>'Transparent subscription-first. No token traps. No forced add-ons. Scale without spiraling costs.','outcome'=>'You know your software cost from day one.'],
        ['icon'=>'🔒','title'=>'Zero AI Lock-In','problem'=>'Locked into a vendor\'s expensive AI provider, paying markup plus subscription.','solution'=>'Bring your own API keys. Use any provider or local models. Or do not use AI at all.','outcome'=>'You control costs and own the relationship with your AI provider.'],
        ['icon'=>'🛡️','title'=>'Zero Data Resale','problem'=>'Vendors monetize your data by selling insights, training AI on jobs, or licensing operating patterns.','solution'=>'Your data is yours. We do not train on it, sell insights, or harvest operational patterns.','outcome'=>'Your competitive advantage stays yours.'],
        ['icon'=>'⚡','title'=>'Zero Workflow Duplication','problem'=>'Fragmented tools force retyping jobs across several apps, wasting hours every week.','solution'=>'One operational record. Every app reads and writes to the same database.','outcome'=>'Technicians clean instead of retype. Real-time truth everywhere.'],
        ['icon'=>'👥','title'=>'Zero Learning Curve','problem'=>'Generic software uses generic terminology that field teams have to translate.','solution'=>'Service Mode terminology, checklists, and training load for your niche.','outcome'=>'Staff use it faster because the interface speaks their language.'],
        ['icon'=>'💼','title'=>'Zero Platform Dependency','problem'=>'Vendor lock-in traps workflows and data inside a black box.','solution'=>'Titan orchestrates. Your processes remain portable. You control your destiny.','outcome'=>'Titan serves you, not the other way around.'],
    ];
@endphp
<div x-data="{ expanded: null, selected: 'residential', modes: @js($modes) }" class="bg-black text-white font-sans overflow-hidden">
    <header class="fixed inset-x-0 top-0 z-50 border-b border-slate-800/80 bg-black/80 backdrop-blur-xl">
        <div class="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
            <a href="/" class="font-black tracking-tight text-xl"><span class="text-blue-400">Titan</span> BOS</a>
            <nav class="hidden items-center gap-5 text-sm text-slate-300 lg:flex">
                <a href="/platform" class="hover:text-white">Platform</a><a href="/apps" class="hover:text-white">Apps</a><a href="/service-modes" class="hover:text-white">Service Modes</a><a href="/industries" class="hover:text-white">Industries</a><a href="/pricing" class="hover:text-white">Pricing</a><a href="/zero-philosophy" class="hover:text-white">Zero</a><a href="/security" class="hover:text-white">Security</a><a href="/ai-strategy" class="hover:text-white">AI</a><a href="/automation-engine" class="hover:text-white">Automation</a><a href="/how-it-works" class="hover:text-white">How It Works</a><a href="/faq" class="hover:text-white">FAQ</a>
            </nav>
            <div class="flex items-center gap-3"><a href="{{ route('login') }}" class="text-sm text-slate-300 hover:text-white">Sign in</a><a href="{{ route('register') }}" class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white hover:bg-blue-700">Start</a></div>
        </div>
    </header>

    <section class="relative flex min-h-screen items-center justify-center overflow-hidden bg-gradient-to-br from-black via-slate-900 to-black px-6 py-28 text-center md:px-12">
        <div class="absolute inset-0 opacity-20"><div class="absolute left-1/4 top-1/4 h-96 w-96 rounded-full bg-blue-600 blur-3xl"></div><div class="absolute bottom-1/4 right-1/4 h-96 w-96 rounded-full bg-cyan-600 blur-3xl"></div></div>
        <div class="grid-bg absolute inset-0 opacity-20"></div>
        <div class="relative z-10 max-w-5xl">
            <h1 class="mb-8 text-7xl font-black leading-tight md:text-9xl"><span class="bg-gradient-to-r from-blue-400 via-cyan-400 to-blue-500 bg-clip-text text-transparent">Titan BOS</span><br><span class="text-white">Zero BS.</span></h1>
            <p class="mx-auto mb-10 max-w-3xl text-2xl font-medium leading-relaxed text-gray-300">The only AI operating system built exclusively for cleaning businesses. Titan runs the business. Zero removes the friction across scheduling, compliance, training, evidence, payments, and the thousands of decisions that drain operator time.</p>
            <div class="flex flex-col justify-center gap-4 sm:flex-row"><a href="{{ route('register') }}" class="rounded-lg bg-blue-600 px-8 py-4 font-bold text-white shadow-lg shadow-blue-600/50 transition hover:bg-blue-700">Start Your Titan System</a><a href="/apps" class="rounded-lg border-2 border-blue-400 px-8 py-4 font-bold text-blue-300 transition hover:bg-blue-400/10">Explore the Apps</a></div>
        </div>
    </section>

    <section class="bg-slate-950 px-6 py-24 md:px-12"><div class="mx-auto max-w-7xl"><h2 class="mb-4 text-center text-5xl font-black md:text-6xl"><span class="bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">The Zero Philosophy</span></h2><p class="mb-16 text-center text-lg text-gray-400">Not branding decoration. Real operating doctrine.</p><div class="grid gap-8 md:grid-cols-2">@foreach($zeroPillars as $pillar)<div class="rounded-lg border border-slate-700 bg-gradient-to-br from-slate-800 to-slate-900 p-8 transition hover:border-blue-500/50 hover:shadow-lg hover:shadow-blue-500/20"><div class="mb-4 flex items-center gap-4"><div class="text-2xl text-blue-400">{{ $pillar['icon'] }}</div><h3 class="text-xl font-bold">{{ $pillar['title'] }}</h3></div><div class="space-y-4 text-sm"><div><p class="mb-1 font-semibold text-gray-500">THE PROBLEM</p><p class="text-gray-300">{{ $pillar['problem'] }}</p></div><div><p class="mb-1 font-semibold text-gray-500">TITAN SOLUTION</p><p class="text-gray-300">{{ $pillar['solution'] }}</p></div><div class="border-t border-slate-700 pt-2"><p class="font-semibold italic text-blue-300">{{ $pillar['outcome'] }}</p></div></div></div>@endforeach</div></div></section>

    <section class="bg-black px-6 py-24 md:px-12"><div class="mx-auto max-w-7xl"><h2 class="mb-16 text-center text-5xl font-black md:text-6xl"><span class="bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">Super Niche AI</span><br><span class="text-white">for Cleaning Operators</span></h2><div class="mb-12 flex flex-wrap justify-center gap-4"><template x-for="(data, key) in modes" :key="key"><button @click="selected=key" :class="selected === key ? 'bg-blue-600 text-white' : 'bg-slate-800 text-gray-300 hover:bg-slate-700'" class="rounded-lg px-6 py-3 font-semibold transition" x-text="data.name"></button></template></div><div class="rounded-xl border border-slate-700 bg-gradient-to-br from-slate-800 to-slate-900 p-8 md:p-12"><h3 class="mb-8 text-3xl font-bold text-cyan-300" x-text="modes[selected].name"></h3><div class="grid gap-8 md:grid-cols-3"><div><h4 class="mb-4 text-sm font-bold uppercase tracking-wide text-gray-400">Niche Workflows</h4><ul class="space-y-3"><template x-for="item in modes[selected].workflows" :key="item"><li class="flex items-start gap-3"><span class="mt-0.5 text-blue-400">✓</span><span class="text-gray-200" x-text="item"></span></li></template></ul></div><div><h4 class="mb-4 text-sm font-bold uppercase tracking-wide text-gray-400">Compliance Logic</h4><ul class="space-y-3"><template x-for="item in modes[selected].compliance" :key="item"><li class="flex items-start gap-3"><span class="mt-0.5 text-blue-400">🛡</span><span class="text-gray-200" x-text="item"></span></li></template></ul></div><div><h4 class="mb-4 text-sm font-bold uppercase tracking-wide text-gray-400">Auto-Generated Artefacts</h4><ul class="space-y-3"><template x-for="item in modes[selected].artifacts" :key="item"><li class="flex items-start gap-3"><span class="mt-0.5 text-blue-400">📘</span><span class="text-gray-200" x-text="item"></span></li></template></ul></div></div></div></div></section>

    <section class="bg-slate-950 px-6 py-24 md:px-12"><div class="mx-auto max-w-7xl"><h2 class="mb-4 text-center text-5xl font-black md:text-6xl"><span class="bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">Up to Nine Apps</span></h2><p class="mb-16 text-center text-lg text-gray-400">One cleaning business operating system.</p><div class="grid gap-6 md:grid-cols-3">@foreach($apps as $idx => $app)<div @click="expanded = expanded === {{ $idx }} ? null : {{ $idx }}" class="group cursor-pointer rounded-lg border border-slate-700 bg-gradient-to-br from-slate-800 to-slate-900 p-6 transition hover:border-blue-500/50"><div class="mb-3 text-4xl">{{ $app['icon'] }}</div><p class="mb-1 text-xs font-bold uppercase tracking-wider text-blue-400">{{ $app['tier'] }}</p><h3 class="mb-1 text-2xl font-bold transition group-hover:text-blue-300">{{ $app['name'] }}</h3><p class="mb-3 text-xs font-semibold italic text-cyan-300">{{ $app['category'] }}</p><p class="mb-4 text-sm text-gray-400">{{ $app['tagline'] }}</p><div class="mb-4 rounded bg-slate-700/50 px-3 py-2 text-xs text-gray-300"><span class="font-bold text-blue-300">Owns: </span>{{ $app['owns'] }}</div><div x-cloak x-show="expanded === {{ $idx }}" class="mt-6 space-y-4 border-t border-slate-700 pt-6"><div><p class="mb-2 text-xs font-bold text-gray-500">CONTROL PLANE</p><ul class="space-y-2">@foreach($app['features'] as $f)<li class="flex items-start gap-2 text-sm text-gray-300"><span class="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-blue-400"></span><span>{{ $f }}</span></li>@endforeach</ul></div><div class="border-t border-slate-700 pt-4"><p class="text-sm font-semibold text-cyan-300">→ {{ $app['impact'] }}</p></div></div></div>@endforeach</div></div></section>

    <section class="bg-black px-6 py-24 md:px-12"><div class="mx-auto max-w-5xl text-center"><h2 class="mb-12 text-5xl font-black md:text-6xl"><span class="bg-gradient-to-r from-blue-400 via-cyan-400 to-blue-500 bg-clip-text text-transparent">Hello Receives. Zero Thinks. Titan Executes.</span></h2><div class="space-y-6 text-lg text-gray-300"><p><span class="font-bold text-blue-400">Hello Receives:</span> Customer books a job. Titan Hello sends confirmation and arrival notice.</p><p><span class="font-bold text-cyan-400">Zero Thinks:</span> AI analyzes job and auto-generates checklist, SWMS, training flow, or artefact as needed.</p><p><span class="font-bold text-blue-400">Titan Executes:</span> Go loads the job. Technician executes. Ground Zero tracks progress. Pro inspects quality. ZeroPay collects payment.</p></div><p class="mt-12 italic text-gray-500">Everything connects. One business. One system. No duplication.</p></div></section>

    <section class="border-t border-slate-700 bg-gradient-to-r from-blue-900/20 to-cyan-900/20 px-6 py-24 md:px-12"><div class="mx-auto max-w-4xl text-center"><h2 class="mb-8 text-4xl font-black">Ready to remove the BS from your cleaning operation?</h2><a href="{{ route('register') }}" class="inline-flex rounded-lg bg-blue-600 px-10 py-5 text-lg font-bold text-white shadow-lg shadow-blue-600/50 transition hover:bg-blue-700">Launch Titan Zero — Start Free Trial</a><p class="mt-6 text-sm text-gray-400">One Service Mode. One app. Zero BS.</p></div></section>

    <footer class="border-t border-slate-800 bg-black px-6 py-12 text-center text-sm text-gray-500 md:px-12"><p>Titan BOS — The operating system for cleaning businesses. Titan Capability. Zero BS.</p></footer>
</div>
</body>
</html>
